version: '3.8'

services:
  api:
    build: ./api
    container_name: api
    environment:
      - ROOT_PATH=/api  # Añade esta variable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.entrypoints=web"
    networks:
      - microservices_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  
  worker:
    build: ./worker
    container_name: worker
    environment:  
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
    volumes:
      - messages_volume:/app/messages
    networks:
      - microservices_net
    depends_on:
      rabbitmq:
        condition: service_healthy  

  # RabbitMQ Service actualizado
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=PathPrefix(`/monitor`)"
      - "traefik.http.routers.rabbitmq.service=rabbitmq"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    healthcheck:  # Nueva sección añadida
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices_net

  # Traefik Service (sin cambios)
  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - microservices_net

volumes:
  messages_volume:
  rabbitmq_data:

networks:
  microservices_net:
    driver: bridge
